### ISSUE TITLE
Missing 23.10.1 tag

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/ayatana-indicator-datetime#121]
As per https://github.com/AyatanaIndicators/ayatana-indicator-datetime/commit/d8debd706fe92de09e5c654c4ea2cc5dd5ce0529 I assume https://github.com/AyatanaIndicators/ayatana-indicator-datetime/releases/tag/23.10.1 should exist?

**Comment by sunweaver** [comment]
Thx, Jami. Pushed now.
