### ISSUE TITLE
date string uses timezone locale, whereas rest of the datetime indicator menu uses $LANG

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-datetime#14]
IMHO, the datestring should comply to the users language settings, not the timezone being in use

![AI-IDO-offscreen-menus_issue-17-img01](https://user-images.githubusercontent.com/407231/90259413-408ab600-de4a-11ea-9694-5dddec648410.png)

The system this screenshot was taken on uses this locale...

**Comment by sunweaver** [comment]
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by sunweaver** [comment]
and why does it have "Berlin" twice in its dialog?

**Comment by tari01** [comment]
> IMHO, the datestring should comply to the users language settings, not the timezone being in use

This is not the indicator, it's a very old (and very frustrating) Ubuntu bug. During setup, the installer asks for the language and time zone. If they don't match (and for many people they don't), Ubuntu sets up a weird language cocktail for your user interface.

On Manjaro, my indicator date is displayed in en_GB.UTF-8 which matches my language preference, although my location(s) have nothing to do with it.

> and why does it have "Berlin" twice in its dialog?

I don't have that, but I guess the first one is probably the "list" of all your locations, and the one with the clock is your current location. I'll check how we can disable it in case of only one location.
