### ISSUE TITLE
Clock stuck on 24hr time when dconf-editor shows 12hr time.

### ISSUE THREAD

**Issue by toola69** [AyatanaIndicators/ayatana-indicator-datetime#27]
Clock stuck on  24hr time when opening dconf-editor shows that the clock is set to 12hr time.
Adding a custom value in dconf-editor doesn't change anything. 
Tried logging out and back in and also restarting.
Have logged the bug with the Ubuntu-Mate launchpad Bug #1922330
They told me to report it upstream.

**Comment by tari01** [comment]
@toola69 

What happens if you change the **time-format** value by toggling the **locale-default** switch?

**Comment by tari01** [comment]
@toola69 

It would be even better if you pasted the output of `dconf dump /org/ayatana/indicator/datetime/` here. Thanks.

**Comment by tari01** [comment]
I'm closing this due to lack of feedback and inability to replicate. If this ever pops up again, feel free to open a bug report.
