### ISSUE TITLE
 Wrong time displayed when LC_TIME=pl_PL.UTF-8 

### ISSUE THREAD

**Issue by piotrjurkiewicz** [AyatanaIndicators/ayatana-indicator-datetime#28]
The time applet on the panel displays time as: "YYYY:MM", YYYY being 4 digit year and MM 2 digit minute. See the attached screenshot:
![169584345_146010740779649_3887427687374594665_n](https://user-images.githubusercontent.com/2237894/114794297-7478fb00-9d8c-11eb-859f-be4a8b60b0b9.jpg)

Steps to replicate on machine configured to any locale:

1. Terminate ayatana-indicator-datetime-service.

2. Run in terminal:

       $ LC_TIME=pl_PL.UTF-8 /usr/libexec/ayatana-indicator-datetime/ayatana-indicator-datetime-service

**Comment by piotrjurkiewicz** [comment]
Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/ayatana-indicator-datetime/+bug/1906238

**Comment by tari01** [comment]
@piotrjurkiewicz 

I tried everything, even setting my `/etc/timezone` to **Europe/Warsaw**, but it displays properly. Could you please do a `dconf dump /org/ayatana/indicator/datetime/` and paste the info here? Thanks.

**Comment by piotrjurkiewicz** [comment]
$ dconf dump /org/ayatana/indicator/datetime/
    [/]
    show-date=false
    show-day=false
    show-seconds=false
    show-year=false

    $ locale
    LANG=en_US.UTF-8
    LANGUAGE=en_US
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC=pl_PL.UTF-8
    LC_TIME=pl_PL.UTF-8
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY=pl_PL.UTF-8
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER=pl_PL.UTF-8
    LC_NAME=pl_PL.UTF-8
    LC_ADDRESS=pl_PL.UTF-8
    LC_TELEPHONE=pl_PL.UTF-8
    LC_MEASUREMENT=pl_PL.UTF-8
    LC_IDENTIFICATION=pl_PL.UTF-8
    LC_ALL=

**Comment by tari01** [comment]
Hm... Everything looks good there, no weird formatting. 

@sunweaver Could you also test this, please? Perhaps it shows up for you...

**Comment by dein0s** [comment]
Having the same issue on Ubuntu MATE 20.10 arm64 edition:
```
# uname -a
Linux pi400 5.13.0-1011-raspi #13-Ubuntu SMP PREEMPT Fri Nov 19 18:40:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```
```
# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```
![2021-12-23_21-42](https://user-images.githubusercontent.com/7908313/147290047-66325c2e-3203-434d-82ef-49e6346277fb.png)

**Comment by Wojtekb30** [comment]
Turn displaying seconds on. It solved the issue for me.

**Comment by piotrjurkiewicz** [comment]
This is still not a solution, because seconds display results in significant higher energy usage in idle.

**Comment by tari01** [comment]
I am very sorry this took so long, but I was finally able to reproduce (and unreproproduce) this issue. Old versions of `ayatana-indicator-datetime` indeed show weird formatting when using certain locales (Polish, most notably). Upgrading the indicator fixes this problem.

Below is a screenshot from a fresh, fully updated Ubuntu MATE 22.04, with the indicator built from the current GitHub code:

![datetime-polish](https://user-images.githubusercontent.com/9939853/216619023-72dda5c0-94c6-4d9b-a41c-91c6ea84cf99.jpg)

You can build it as follows:

First kill the running instance of `ayatana-indicator-datetime` in your System Monitor, then:
```
sudo apt update
sudo apt upgrade
sudo apt install cmake cmake-extras dbus intltool libaccounts-glib-dev libayatana-common-dev libglib2.0-dev libnotify-dev libgstreamer1.0-dev libecal2.0-dev libical-dev libedataserver1.2-dev libproperties-cpp-dev libmessaging-menu-dev uuid-dev git
git clone https://github.com/AyatanaIndicators/ayatana-indicator-datetime.git
cd ayatana-indicator-datetime
mkdir build
cd build
cmake ..
make
sudo make install
LC_TIME=pl_PL.UTF-8 /usr/libexec/ayatana-indicator-datetime/ayatana-indicator-datetime-service
```
Please report back here if this works for you. Thanks.

**Comment by pbedn** [comment]
In Ubuntu 22.10 problem still persist. And I can't build new version from git as I am unable to install: libecal2.0-dev and libedataserver1.2-dev.

`The following packages have unmet dependencies:
 libecal2.0-dev : Depends: libecal-2.0-2 (= 3.46.0-1) but 3.46.1-0ubuntu1 is to be installed
 libedataserver1.2-dev : Depends: libedataserver-1.2-27 (= 3.46.0-1) but 3.46.1-0ubuntu1 is to be installed
                         Depends: libcamel1.2-dev (= 3.46.0-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by tari01** [comment]
I am closing this as multiple users have confirmed that running the latest code snapshot fixes this issue.
