### ISSUE TITLE
Lack of right padding leaves indicator off-centre

### ISSUE THREAD

**Issue by fossfreedom** [AyatanaIndicators/ayatana-indicator-datetime#56]
![Screenshot from 2021-10-09 18-46-18](https://user-images.githubusercontent.com/996240/136669245-fcbf711e-a7c7-4d89-9b1d-055d81df9f79.png)

This is via ubuntu-budgie 21.10 built with ayatana-indicators support.

Other indicators such as indicator-multiload display ok.  It doesnt appear to be theme dependent - I've tried Arc, Yaru etc and all display similarly without right-padding.

Thoughts?

**Comment by sunweaver** [comment]
@tari01: can you confirm this? Can we amend this before the 0.9.0 release?

**Comment by sunweaver** [comment]
@fossfreedom: are you using the latest Git versions of Ayatana Indicators for testing? Or the versions that you find in Ubuntu 21.10?

**Comment by tari01** [comment]
@fossfreedom @sunweaver 

The Indicators do not set the "look", only the "feel". How things appear depends on the theme. Most of them are not 100% Ayatana-aware. Currently, I can only recommnend Ubuntu MATE's **Ambiant-MATE** for testing.

**Comment by fossfreedom** [comment]
@sunweaver the version of ayatana indicator date time is this - https://packages.ubuntu.com/impish/ayatana-indicator-datetime 0.8.1-2ubuntu1 - this appears to be the latest available since liblomiri-url-dispatcher-dev is a missing dependency even in 22.04 https://launchpad.net/ubuntu/+source/ayatana-indicator-datetime/0.8.3-1/+build/22315926

**Comment by fossfreedom** [comment]
@tari01 ambiant-mate has the same issue as well

**Comment by tari01** [comment]
@fossfreedom @sunweaver 

I went through the code for all IDO components and indicators to see what exactly we do on the Ayatana side:

- All our menu items have a hard-coded **6px** right margin
- Many moons ago, I have added extra **16px** to the volume slider to make it look more centred (I think it was a bad choice, although it looks better)
- All other items are controlled by the theme

Choice 1: I could hack some end-margin into the calendar IDO item, just like I did with the volume scale IDO item
(This would give us instant results, but not guarantee cross-theme consistemcy)
Choice 2: Remove the scale item hack, leave the calendar item alone, and let themes tweak Ayatana the way they like
(The proper way to do it, but would take some time before themes adapt)

I prefer the second, but I would like to heard from both of you regarding this.

**Comment by fossfreedom** [comment]
If the intention is todo option 2 then please can a better style class names be used for the calendar. See my gtk inspector picture. Style classes shouldn't really have periods in the name since the you have to use really weird syntax. 

Also I didn't see any style class names for the menu item labels below so again it makes specific  targeted styling very difficult without a name.

**Comment by tari01** [comment]
I have removed the the volume slider hack. With a current build from Git, the styling can be done like this:

```
#org\.ayatana\.indicator\.slider
{
    padding-right: 20px;
}

#org\.ayatana\.indicator\.calendar
{
    padding-right: 20px;
}

#org\.ayatana\.indicator\.appointment
{
    padding-right: 20px;
}

#org\.ayatana\.indicator\.location
{
    padding-right: 20px;
}
```

Class name changes are on my TODO. Closing.
