### ISSUE TITLE
Disabling Mir from package for Debian derivates

### ISSUE THREAD

**Issue by fossfreedom** [AyatanaIndicators/ayatana-indicator-datetime#83]
All,

  For Ubuntu 22.04 the sync from Debian for a lot of the ayatana packages are not being released due to Mir issues & dependencies - I presume because the Mir version in Debian is too old compared to Ubuntu?

Rather than do a ubuntu specific patch that will stop sync's working from Debian to Ubuntu - is it worth adding a debian/rules/control change to disable/remove Mir building and dependencies for Debian derivates? - I'm obviously assuming here there is a way to disable building using Mir.

**Comment by sunweaver** [comment]
@fossfreedom: the solution to this is now available with Ayatana Indicators 0.9.x.

The lomiri (and Mir) specific stuff has been moved into libayatana-common. In Ubuntu, you have to provide a libayatana-common that has been built without lomiri-url-dispatcher as a build dependency. Then all Ayatana Indicators should be usable on Ubuntu.

**Comment by sunweaver** [comment]
Also, I have just merge #82 for the datetime indicator which should make it possible to build a datetime indicator with Lomiri features enabled or disabled (default: disabled).

So, please try the libayatana-common adjustment (omitting liblomiri-url-dispatcher-dev from build-dependencies).

I will file a bug against libayatana-common to add a build option to explicitly enable/disable url-dispatcher (not just by having it in build-depends field or not).

**Comment by fossfreedom** [comment]
Many thanks for the info and cheers for filing the issue https://github.com/AyatanaIndicators/libayatana-common/issues/51
