### ISSUE TITLE
Test failure on Alpine Linux

### ISSUE THREAD

**Issue by z3ntu** [AyatanaIndicators/ayatana-indicator-datetime#85]
Hi, I'm getting this test failure, do you have an idea what could cause this?
```
[ RUN      ] FormatterFixture.TestUpcomingTimes
/home/pmos/build/src/ayatana-indicator-datetime-0.9.0/tests/test-formatter.cpp:203: Failure
Expected equality of these values:
  test_case.expected_format_string
    Which is: "%l:%M %p"
  fmt
    Which is: "%H:%M"
[  FAILED  ] FormatterFixture.TestUpcomingTimes (0 ms)
```
To note, Alpine uses busybox utils by default so `date` is not from GNU coreutils (unless specifically installed), not sure what this indicator does though

**Comment by tari01** [comment]
> test-formatter

1. Do you have the `locales` package installed?
2. Is this the only thing that fails when running tests?
3. Could you please look at this section: https://github.com/AyatanaIndicators/ayatana-indicator-datetime/blob/291efbd3b225c0760b9407370e1643c1b239aff8/.build.yml#L37, install all the listed dependencies, then run the tests again?

Thanks.

**Comment by z3ntu** [comment]
```
Test project /home/pmos/build/src/ayatana-indicator-datetime-0.9.0/build
      Start  1: test-datetime
 1/25 Test  #1: test-datetime ..........................................   Passed    0.06 sec
      Start  2: test-actions
 2/25 Test  #2: test-actions ...........................................   Passed    0.55 sec
      Start  3: test-alarm-queue
 3/25 Test  #3: test-alarm-queue .......................................   Passed    0.23 sec
      Start  4: dear-reader-the-next-test-takes-60-seconds
 4/25 Test  #4: dear-reader-the-next-test-takes-60-seconds .............   Passed    0.00 sec
      Start  5: test-clock
 5/25 Test  #5: test-clock .............................................   Passed   61.16 sec
      Start  6: test-formatter
 6/25 Test  #6: test-formatter .........................................***Failed    0.01 sec
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from FormatterFixture
[ RUN      ] FormatterFixture.TestUpcomingTimes
/home/pmos/build/src/ayatana-indicator-datetime-0.9.0/tests/test-formatter.cpp:203: Failure
Expected equality of these values:
  test_case.expected_format_string
    Which is: "%l:%M %p"
  fmt
    Which is: "%H:%M"
[  FAILED  ] FormatterFixture.TestUpcomingTimes (1 ms)
[ RUN      ] FormatterFixture.TestEventTimes
[       OK ] FormatterFixture.TestEventTimes (0 ms)
[----------] 2 tests from FormatterFixture (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FormatterFixture.TestUpcomingTimes

 1 FAILED TEST
  YOU HAVE 2 DISABLED TESTS


      Start  7: test-live-actions
```
and the last test hangs (maybe a missing dependency, haven't checked closer yet).

I've looked a bit closer now into the implementation of the time formatting test, and it basically sets `LC_TIME` to `en_US.UTF-8`, and then I think uses `src/utils.c` `is_locale_12h` which gets `nl_langinfo(T_FMT)` and hopes to get a 12 hour AM/PM formatting string back. The problem is that musl libc doesn't really have much locale support, so it always returns `%H:%M:%S` for `T_FMT` regardless of `LC_TIME` or other variables. It only gives the formatting string `%I:%M:%S %p` when requested, so by using `T_FMT_AMPM`. Basically an application cannot rely on musl libc to return locale-adjusted things.

**Comment by sunweaver** [comment]
@z3ntu so maybe skip that test when building against musl libc?

**Comment by z3ntu** [comment]
Ok I'm skipping `ctest -E "test-formatter"` now, the rest of the tests are fine.

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/30508/diffs

I think we can close this then? Nothing really to do from your side as you expect libc to provide some locale support.
