### ISSUE TITLE
Missing time in panel indicator

### ISSUE THREAD

**Issue by Rantyrant** [AyatanaIndicators/ayatana-indicator-datetime#95]
So the time is missing from the indicator on the panel in Ubuntu Mate 22.04, and I'm not quite sure why.
Originally created a bug report on launchpad for this for Ubuntu Mate 21.10 and 22.04 (but they couldn't replicate it), but it also happens when built from git on Arch Linux, also happens on Debian Sid with packages from the repo. 

Attachment shows the issue best, the recording is from a VM of Ubuntu Mate 22.04 (fully upgraded), but it happens on the live media, too, as well as on actual install.

![missing-time-in-datetime](https://user-images.githubusercontent.com/65864655/182028447-e73f18fd-5c74-4cb1-b79a-4e3dcc1f73fd.gif)

**Comment by tari01** [comment]
@Rantyrant:

Can you please post the output of your `locale` command? Thanks.

**Comment by Rantyrant** [comment]
This is from 22.10 ubuntu-mate live iso.

`ubuntu-mate@ubuntu-mate:~$ locale
LANG=da_DK.UTF-8
LANGUAGE=
LC_CTYPE="da_DK.UTF-8"
LC_NUMERIC="da_DK.UTF-8"
LC_TIME="da_DK.UTF-8"
LC_COLLATE="da_DK.UTF-8"
LC_MONETARY="da_DK.UTF-8"
LC_MESSAGES="da_DK.UTF-8"
LC_PAPER="da_DK.UTF-8"
LC_NAME="da_DK.UTF-8"
LC_ADDRESS="da_DK.UTF-8"
LC_TELEPHONE="da_DK.UTF-8"
LC_MEASUREMENT="da_DK.UTF-8"
LC_IDENTIFICATION="da_DK.UTF-8"
LC_ALL=
`

**Comment by tari01** [comment]
I would like to ask you to test the current code following the instructions here: https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/28#issuecomment-1415916901.

You should edit the call to the indicator service:

`LC_TIME=da_DK.UTF-8 /usr/libexec/ayatana-indicator-datetime/ayatana-indicator-datetime-service`

or simply

`/usr/libexec/ayatana-indicator-datetime/ayatana-indicator-datetime-service`

Please report back if it works for you. In case there are no issues, you can (hopefully) close this report.

**Comment by Rantyrant** [comment]
Yep, it seems to be fixed with the git version. I'll close it as fixed. :)
