### ISSUE TITLE
Lomiri: Vibration during alarm doesn't work

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/ayatana-indicator-datetime#96]
On Ubuntu Touch 20.04 alarms set with [Clock app](https://gitlab.com/ubports/development/apps/clock-app/-/merge_requests/198) don't have vibration and the attempts seemingly results in the following getting printed in `systemctl --user` logs every 2 seconds while the alarm is going off:
```
Sep 08 12:05:13 ubuntu-phablet ayatana-indicat[2287]: g_variant_builder_init: assertion 'g_variant_type_is_container (type)' failed
Sep 08 12:05:13 ubuntu-phablet ayatana-indicat[2287]: g_variant_builder_add_value: assertion 'ensure_valid_builder (builder)' failed
Sep 08 12:05:13 ubuntu-phablet ayatana-indicat[2287]: g_variant_builder_end: assertion 'ensure_valid_builder (builder)' failed
```
Related changes were done in #78 by @tari01 to make the vibration work via `hfd-service` but it doesn't seem to work (anymore?); `hfd-service-tools-vibrator` (from `hfd-service-tools`) does work just fine so vibration in general is ok.

**Comment by tari01** [comment]
@JamiKettunen: Could you please check if https://github.com/AyatanaIndicators/ayatana-indicator-datetime/pull/101 fixes this? Thanks.
