### ISSUE TITLE
Lomiri: Expanded time widget doesn't take timezone into account

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/ayatana-indicator-datetime#97]
On Ubuntu Touch 20.04 the time "preview" in top bar is correct, but the widget itself when dragged down shows the clock without timezone offset (stays at `UTC+0` instead of `UTC+3` in my case):
<img src="https://user-images.githubusercontent.com/47358222/189358006-69374eef-41f6-46d7-9c50-709496120cbe.png" width=400 />
The shown timezone (`Helsinki`) is correct as well though, just the shown time (`11:19:00`) is incorrect.

This should be reproducible with [the UBports PDK](https://github.com/ubports/ubports-pdk) but I didn't check, only on hardware (Volla Phone w/ UT 20.04).

**Comment by tari01** [comment]
@JamiKettunen

I have debugged the life out of this. The DateTime Indicator always passes the correct time zone + time format to the bus (I worked with Helsinki, just to be sure). The indicator itself does not set the time value, that is being done by something called `timeZoneMenu` in Lomiri. I've tried to figure out where the value changes, but it's all qml.

We need somebody who can understand qml code and continue from there.

**Comment by sunweaver** [comment]
@JamiKettunen Maybe it relates to this: The indicators get started by systemd while Lomiri shell runs in full user context (guessing a bit here). May it be that the system runs in UTC+0 while the user shell runs in UTC+3?

**Comment by mariogrip** [comment]
This seems fine for me in latest rev

**Comment by JamiKettunen** [comment]
Can confirm @mariogrip's findings on UT 20.04 with both Volla Phone (r346) and Volla Phone 22 (r37), closing :)
